name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/terndata.flux
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build
      - name: Build package
        run: |
          python -m build  # python setup.py sdist bdist_wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Build with Read the Docs
        uses: readthedocs/readthedocs-build@v1
        with:
          project: 'terndata.flux'
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload the generated readthedocs doc artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_build/html'